Repository AY2425S1-CS2103T-F10-3/tp, pull requests merged in 2024-10, with the labels that each got.

#6 Add wei bin photo
  docs/images/lowweibin.png
Labels: priority.High

#9 Add Isaac photo
  docs/images/itzxitzx.png
Labels: priority.High

#60 Create AddBuyCommandParser with dummy return values
  src/main/java/seedu/address/logic/parser/AddBuyCommandParser.java
  src/test/java/seedu/address/logic/parser/AddBuyCommandParserTest.java
Labels: type.Task, priority.High

#57 Added new Properties parent classes and subclasses + Edited Command class for new AddPropertyToSellCommand
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/AddPropertyToSellCommand.java
  src/main/java/seedu/address/logic/parser/AddPropertyToSellParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Apartment.java
  src/main/java/seedu/address/model/person/Bto.java
  src/main/java/seedu/address/model/person/Condo.java
  src/main/java/seedu/address/model/person/Hdb.java
  src/main/java/seedu/address/model/person/HousingType.java
  src/main/java/seedu/address/model/person/OtherProperty.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PostalCode.java
  src/main/java/seedu/address/model/person/Price.java
  src/main/java/seedu/address/model/person/Property.java
  src/main/java/seedu/address/model/person/UnitNumber.java
  src/test/java/seedu/address/logic/commands/AddPropertyToSellCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High

#68 Working on AddSellProperty command /addSell
  src/main/java/seedu/address/logic/commands/AddPropertyToSellCommand.java
  src/main/java/seedu/address/logic/parser/AddPropertyToSellParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Apartment.java
  src/main/java/seedu/address/model/person/Bto.java
  src/main/java/seedu/address/model/person/Condo.java
  src/main/java/seedu/address/model/person/Hdb.java
  src/main/java/seedu/address/model/person/OtherProperty.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Property.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPropertyToSellCommandTest.java
  src/test/java/seedu/address/logic/parser/AddPropertyToSellParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/ApartmentTest.java
  src/test/java/seedu/address/model/person/BtoTest.java
  src/test/java/seedu/address/model/person/CondoTest.java
  src/test/java/seedu/address/model/person/HdbTest.java
  src/test/java/seedu/address/model/person/OtherPropertyTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PropertyTest.java
  src/test/java/seedu/address/testutil/IndexBuilder.java
Labels: priority.High

#72 Add delete property to buy command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeletePropertyToBuyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeletePropertyToBuyCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeletePropertyToBuyCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeletePropertyToBuyCommandParserTest.java
  src/test/java/seedu/address/testutil/CondoToBuyBuilder.java
  src/test/java/seedu/address/testutil/CondoToSellBuilder.java
  src/test/java/seedu/address/testutil/EditPersonPropertyDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PropertyToSellBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#86 implement-DeletePropertyToBuyCommand
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeletePropertyToBuyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeletePropertyToBuyCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeletePropertyToBuyCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeletePropertyToBuyCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonPropertyDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalProperties.java
Labels: type.Task, priority.High

#88 Updated Documentation
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/find87438807_99272758Result.png
  docs/images/findAlexDavidResult.png
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddPropertyToBuyCommand.java
  src/main/java/seedu/address/logic/commands/AddPropertyToSellCommand.java
  src/main/java/seedu/address/logic/commands/FindNameCommand.java
  src/main/java/seedu/address/logic/commands/FindPhoneNumberCommand.java
  src/main/java/seedu/address/logic/parser/AddPropertyToBuyParser.java
  src/main/java/seedu/address/logic/parser/AddPropertyToSellParser.java
  src/main/java/seedu/address/logic/parser/FindPhoneNumberCommandParser.java
  src/main/java/seedu/address/model/person/Bto.java
  src/main/java/seedu/address/model/person/Condo.java
  src/main/java/seedu/address/model/person/Hdb.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/OtherProperty.java
  src/main/java/seedu/address/model/person/PhoneNumberContainsKeywordPredicate.java
  src/main/java/seedu/address/model/person/Property.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/parser/FindPhoneNumberCommandParserTest.java
Labels: priority.High

#94 Add 1 more known issue about delSell and delBuy
  docs/UserGuide.md
Labels: type.Bug

#104 Edit the List to Observable List to fix Ui
  src/main/java/seedu/address/logic/commands/DeletePropertyToBuyCommand.java
  src/main/java/seedu/address/logic/commands/DeletePropertyToSellCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High

#113 Add a new sort individual command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SortIndividualCommand.java
  src/main/java/seedu/address/logic/parser/AddPropertyToSellParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/SortIndividualCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Price.java
  src/test/java/seedu/address/logic/commands/SortIndividualCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SortIndividualCommandParserTest.java
  src/test/java/seedu/address/model/person/PriceTest.java
Labels: priority.High

#110 Add command history feature
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/resources/view/CommandBox.fxml
Labels: priority.Medium

#122 Update UML diagram for ModelClassDiagram
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task

#128 Implement bought and sold command
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/BoughtPropertyCommand.java
  src/main/java/seedu/address/logic/commands/DeletePropertyToBuyCommand.java
  src/main/java/seedu/address/logic/commands/DeletePropertyToSellCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/SoldPropertyCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/BoughtPropertyCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/SoldPropertyCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Apartment.java
  src/main/java/seedu/address/model/person/Bto.java
  src/main/java/seedu/address/model/person/Condo.java
  src/main/java/seedu/address/model/person/Hdb.java
  src/main/java/seedu/address/model/person/OtherProperty.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Price.java
  src/main/java/seedu/address/model/person/Property.java
  src/main/java/seedu/address/model/person/UniqueBuyingPropertyList.java
  src/main/java/seedu/address/model/person/UniqueSellingPropertyList.java
  src/main/java/seedu/address/model/statistics/AddressBookStatistics.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/BoughtPropertyCommandTest.java
  src/test/java/seedu/address/logic/commands/SoldPropertyCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/BoughtPropertyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/SoldPropertyCommandParserTest.java
  src/test/java/seedu/address/model/person/ApartmentTest.java
  src/test/java/seedu/address/model/person/BtoTest.java
  src/test/java/seedu/address/model/person/CondoTest.java
  src/test/java/seedu/address/model/person/HdbTest.java
  src/test/java/seedu/address/model/person/OtherPropertyTest.java
  src/test/java/seedu/address/model/person/PropertyTest.java
  src/test/java/seedu/address/model/person/UniqueBuyingPropertyListTest.java
  src/test/java/seedu/address/model/person/UniqueSellingPropertyListTest.java
  src/test/java/seedu/address/model/statistics/AddressBookStatisticsTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/AddressBookStatisticsBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PropertyToBuyBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalProperties.java
Labels: type.Task, priority.High

#145 Updated User Guide
  docs/UserGuide.md
  docs/images/FindCommand.png
  docs/images/SortCommand.png
  docs/images/addBuy.png
  docs/images/addName.png
  docs/images/addSell.png
  docs/images/boughtCommand.png
  docs/images/clearMessage.png
  docs/images/delBuy.png
  docs/images/delSell.png
  docs/images/deleteContact.png
  docs/images/editMessage.png
  docs/images/findProperty.png
  docs/images/pinCommand.png
  docs/images/soldCommand.png
  docs/images/sortiCommand.png
  downloads
  downloads.pub
Labels: type.Enhancement, priority.High
