Repository AY2425S1-CS2103T-F10-3/tp, pull requests merged in 2024-11, with the labels that each got.

#130 Fix a minor Ui bug
  docs/DeveloperGuide.md
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/logic/commands/AddPropertyToSellCommand.java
  src/main/java/seedu/address/logic/parser/AddPropertyToBuyParser.java
  src/main/java/seedu/address/logic/parser/AddPropertyToSellParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortIndividualCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/AddPropertyToSellCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/PropertyBuilder.java
Labels: priority.High, alpha-bug

#146 Fix sort and pin
  docs/UserGuide.md
  docs/images/unpinCommand.png
  src/main/java/seedu/address/logic/commands/PinContactCommand.java
  src/main/java/seedu/address/logic/commands/UnpinContactCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UnpinContactCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/PinContactCommandTest.java
  src/test/java/seedu/address/logic/commands/UnpinContactCommandTest.java
  src/test/java/seedu/address/logic/parser/UnpinContactCommandParserTest.java
Labels: alpha-bug

#144 Minor UI changes
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddPropertyToBuyCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddPropertyToSellParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/images/email.png
  src/main/resources/images/map-marker.png
  src/main/resources/images/phone-classic.png
  src/main/resources/images/want-to-buy.png
  src/main/resources/images/want-to-sell.png
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: priority.Medium

#158 Feature stats command
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/StatisticsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/statistics/AddressBookStatistics.java
  src/test/java/seedu/address/logic/commands/StatisticsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task, priority.High

#170 Update pin to be persistent
  src/main/java/seedu/address/logic/commands/DeletePropertyToBuyCommand.java
  src/main/java/seedu/address/logic/commands/DeletePropertyToSellCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: alpha-bug

#190 Update UG
  docs/UserGuide.md
Labels: alpha-bug

#191 Fix alpha bugs + Update Developer Guide Use Cases
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/statsCommand.png
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/PinContactCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/SortIndividualCommand.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
Labels: type.Task, alpha-bug

#271 Fix minor bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug

#278 Fix v1.6 bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug
